### ISSUE TITLE
Binary 58b can't be read, every other program can

### ISSUE THREAD

**Issue by sveselinovic** [openmodal/pyuff#38]
Hi,

I have some .uff files in binary and non-binary format, exported from the same program. The binary 58b blocks cannot be read, while the 58 can. I can read the binary files without any problems in MATLAB and Siemens TestLab. Is pyuff erronous or the programs uff exporter? I have uploaded the file. The error does not tell me much except that it can't be read. Other blocks like the two headers can be read btw.

[test.zip](https://github.com/openmodal/pyuff/files/6405671/test.zip)

**Comment by jankoslavic** [comment]
Dear @sveselinovic ! can you please share a sort shipped how do you import the dataset?

**Comment by sveselinovic** [comment]
In the (I think?) simplest way, I read the uff file and then read all data sets.

```python
uff_file = pyuff.UFF('./uff/' + name) 
data = uff_file.read_sets()
```

It also happens when reading a single 58b data set (i.e. the 10th).

**Comment by jankoslavic** [comment]
@sveselinovic I have checked your data. 
the error is in the line (https://github.com/openmodal/pyuff/blob/5586224dce193b65867c65877d2408391fb788e0/pyuff.py#L1428):
values = np.asarray(struct.unpack('%c%sd' % (bo, int(len(split_data) / 8)), split_data), 'd')

where the `split_data` has the content: 
`...\xcf x\xb4u\xb6\xb6?\n`
the additional `\n` should not be there as far as I am aware (and is not there with other 58b test files we have and as far as I understand the standard).
A workaround for your case would be:
np.asarray(struct.unpack('%c%sd' % (bo, int(len(split_data[:-1]) / 8)), split_data[:-1]), 'd')
but this is not to be implemented in the main branch as this would break other test cases. 

This issue is also related with https://github.com/openmodal/pyuff/issues/9.

If you see a elegant solution, you are welcome with a PR.
Regards,
JS

**Comment by sveselinovic** [comment]
@jankoslavic thank you for your help, we will look into fixing our export.
